[build]
  publish = "dist/"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18.20.2"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
                  default-src 'self'; 
                  connect-src 'self' https://dummyjson.com https://picsum.photos;
                  script-src 'self'; 
                  style-src 'self';
                  img-src 'self';
                """